apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: doms_cluster
  region: us-east-1
  version: "1.17"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-09d0e450bb44a1ec6 }
      us-east-1b: { id: subnet-09afa2d8b0181499f }
      us-east-1c: { id: subnet-03ed89057736e257d }
    public:
      us-east-1a: { id: subnet-01b9cc3d7d01d90cc }
      us-east-1b: { id: subnet-0943c06bf350ec9fe }
      us-east-1c: { id: subnet-021e8d35c83860c06 }
  
managedNodeGroups:
  - name: doms_cluster-workers
    minSize: 3
    maxSize: 6
    desiredCapacity: 3
    instanceType: m5.2xlarge
    labels: {role: worker}
    ssh:
      publicKeyName: joaquin
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true